### ISSUE TITLE
Azure Build: Add Book Page

### ISSUE THREAD

**Issue by sophie-haynes** [sophie-haynes/TeamSophie#2]
This is a single page requiring build. See diagram for specific details.
[2017-11-09 16.33.23.pdf](https://github.com/sophie-haynes/TeamSophie/files/1491862/2017-11-09.16.33.23.pdf)

**Comment by AMacleod79** [comment]
![panel_addbook](https://user-images.githubusercontent.com/15485951/33133449-b9d20292-cf94-11e7-887e-ce3716b27894.png)

**Comment by AMacleod79** [comment]
add book page image. attaching file in new commit
