### ISSUE TITLE
Axure Functionality: Add onClick Functionality to Book Details Page

### ISSUE THREAD

**Issue by sophie-haynes** [sophie-haynes/TeamSophie#21]
Add onClick functionality to all buttons on page

* For logged in users screen: "Buy" moves to checkout page
* Not logged in users: "Buy" button produces warning they need to sign in

**Comment by SamMcRuvie** [comment]
@sophie-haynes @dhcfalcon96 for the warning message, should it be a push notification? and if so i think we should design a master one that can be copy and pasted to maintain consistency if it needs to be used on multiple screen.

**Comment by sophie-haynes** [comment]
Push notification? You mean a pop up one yeah? A master one sounds smart

**Comment by SamMcRuvie** [comment]
Yeah I mean popup. I will make one on the not signed version of book details page and we can all reuse it throughout the app where need.

**Comment by sophie-haynes** [comment]
👍 That sounds perfect!!

**Comment by SamMcRuvie** [comment]
Added the functionality for the logged in users as well as non-logged in users. Popup on non-logged in version is the default IOS alert, will need to run this by the client if possible or make a decision whether we wish to change it to a custom build one.

**Comment by SamMcRuvie** [comment]
I can't add functionality to the Back Chevron on either of the versions of this page. The Back Chevron is a master element which doesn't allow me to edit the properties. I would change this my self however it may mess-up the nav bar on other pages. @dhcfalcon96 would be best suited to make the changes to the master element.

**Comment by AMacleod79** [comment]
so I managed to add the functionality to the dynamic panel by adding an on click function back to the appropriate page

**Comment by SamMcRuvie** [comment]
@dhcfalcon96 fix the Back Chevron functionality.
