### ISSUE TITLE
Axure Build: Profile Page

### ISSUE THREAD

**Issue by sophie-haynes** [sophie-haynes/TeamSophie#4]
Single page required. See diagram for details.
[2017-11-09 16.31.38.pdf](https://github.com/sophie-haynes/TeamSophie/files/1491913/2017-11-09.16.31.38.pdf)

**Comment by dhcfalcon96** [comment]
![image](https://user-images.githubusercontent.com/15932825/33138038-6b390fce-cfa1-11e7-9a5a-4c0363b27e74.png)

Colour scheme not final- had some major issues changing it from here, could not sort solution.

For the layout, those headers towards the bottom of the page are likely gonna need to turn into linked pages, but can explain in depth tomorrow.

Ignore my last one, I accidentally posted to the wrong channel
