### ISSUE TITLE
Axure Build: Search Result Page

### ISSUE THREAD

**Issue by sophie-haynes** [sophie-haynes/TeamSophie#6]
Similar to the home page. See diagram for additional filter features.
[2017-11-09 16.31.38.pdf](https://github.com/sophie-haynes/TeamSophie/files/1491934/2017-11-09.16.31.38.pdf)

**Comment by AMacleod79** [comment]
![panel_searchresults](https://user-images.githubusercontent.com/15485951/33135977-e91e3956-cf9b-11e7-8454-bebde7104247.png)

**Comment by AMacleod79** [comment]
search results page

**Comment by sophie-haynes** [comment]
Perfect!
