### ISSUE TITLE
Axure Build: Login Page + Design

### ISSUE THREAD

**Issue by sophie-haynes** [sophie-haynes/TeamSophie#7]
There is no current design for the login. Follow the design for sign up and change accordingly. See diagram for details. 
[2017-11-09 16.33.23.pdf](https://github.com/sophie-haynes/TeamSophie/files/1492109/2017-11-09.16.33.23.pdf)

**Comment by AMacleod79** [comment]
![keedologin](https://user-images.githubusercontent.com/15485951/33124185-2a39c91e-cf74-11e7-9225-0d51667b062e.png)

**Comment by AMacleod79** [comment]
here's the png export for the login. Will commit the axure file now
